# Generated by Django 2.1.4 on 2018-12-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='new_field',
            field=models.TextField(default=''),
        ),
    ]
