# Generated by Django 2.1.4 on 2018-12-27 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181227_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='new_field',
            new_name='desc',
        ),
    ]
