# Generated by Django 2.1.4 on 2019-01-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190104_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='img_capa',
        ),
    ]
